config/routes.rb
Rails.application.routes.draw do
  resources :topics do
 # #34
     resources :posts, except: [:index] do
       resources :comments, only: [:create, :destroy]
       resources :favorites, only: [:create, :destroy]
     end
     resources :sponsored_posts, except: [:index]
  end

  post '/up-vote/:post_id' => 'votes#up_vote', as: :up_vote
  post '/down-vote/:post_id' => 'votes#down_vote', as: :down_vote

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]


  resources :advertisements

  resources :questions

  get 'about' => 'welcome#about'

  root 'welcome#index'

  get 'faq' => 'welcome#faq'

  post 'users/confirmation' => 'users#confirmation'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, length: { minimum: 5 }, presence: true
  validates :user, presence: true
  after_create :send_favorite_emails

   private

   def send_favorite_emails
     post.favorites.each do |favorite|
       FavoriteMailer.new_comment(favorite.user, post, self).deliver_now
     end
   end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  after_create :create_favorite

  default_scope { order('rank DESC') }
  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }

  scope :ordered_by_title, -> { order('title DESC') }
  scope :ordered_by_reverse_created_at, -> { order('created_at ASC') }
  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true
  def up_votes
 # #9
    votes.where(value: 1).count
  end

  def down_votes
 # #10
    votes.where(value: -1).count
  end
  def update_rank
     age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
     new_rank = points + age_in_days
     update_attribute(:rank, new_rank)
  end

  def points
 # #11
    votes.sum(:value)
  end
  def create_vote
    user.votes.create(value: 1, post: self)
  end
  def create_favorite
    Favorite.create(post: self, user: self.user)
    FavoriteMailer.new_post(self, self.user).deliver_now
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
end

app/models/question1.rb
class Question < ApplicationRecord
  has_many :answers
end

app/models/sponsored_post.rb
class SponsoredPost < ApplicationRecord
  has_many :posts
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy

  validates :name, length: { minimum: 5 }, presence: true
  validates :description, length: { minimum: 15 }, presence: true
  before_save :set_public

  private
  def set_public
    self.public = true if self.public == nil
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  before_save { self.email = email.downcase if email.present? }
  before_save { self.role ||= :member }
  before_save :format_name

 # #3
  validates :name, length: { minimum: 1, maximum: 100 }, presence: true
 # #4
  validates :password, presence: true, length: { minimum: 6 }, if: "password_digest.nil?"
  validates :password, length: { minimum: 6 }, allow_blank: true
 # #5
  validates :email,
             presence: true,
             uniqueness: { case_sensitive: false },
             length: { minimum: 3, maximum: 254 }

 # #6
  has_secure_password
  enum role: [:member, :admin, :moderator]
  def format_name
   if name
      name_array = []
      name.split.each do |name_part|
        name_array << name_part.capitalize
      end

      self.name = name_array.join(" ")
    end
  end
  def favorite_for(post)
     favorites.where(post_id: post.id).first
  end
  def avatar_url(size)
     gravatar_id = Digest::MD5::hexdigest(self.email).downcase
     "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
   end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :post
  after_save :update_post

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true
  private

  def update_post
    post.update_rank
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end
  def show
    @question = Question.find(params[:id])
  end
  def new
    @question = Question.new
  end
  def create
    @question = Question.new
    @question.title = params[:question][:title]
    @question.body = params[:question][:body]
    @question.resolved = params[:question][:resolved]

    if @question.save
 # #11
      flash[:notice] = "Question was saved."
      redirect_to @question
    else
 # #12
      flash.now[:error] = "There was an error saving the Question. Please try again."
      render :new
    end
  end
  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(param.require(:question).permit(:title, :body, :resolved))
      flash[:notice] = "Question was updated."
      redirect_to @question
    else
      flash[:error] = "There was an error saving the question. Please try again."
      render :edit
    end
  end
  def destroy
    @question = Question.find(params[:id])

    if @question.destroy
      flash[:notice] = "\"#{@question.title}\" was deleted successfully."
      redirect_to questions_path
    else
      flash[:error] = "There was an error deleting the question."
      render :show
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
     css_class = 'form-group'
     css_class << ' has-error' if errors.any?
# #5
     content_tag :div, capture(&block), class: css_class
   end
   def avatar_url(user)
     gravatar_id = Digest::MD5::hexdigest(user.email).downcase
     "http://gravatar.com/avatar/#{gravatar_id}.png?s=48"
   end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def user_is_authorized_for_comment?(comment)
      current_user && (current_user == comment.user || current_user.admin?)
   end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_is_authorized_for_post?(post)
        current_user && (current_user == post.user || current_user.admin?)
   end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def create_session(user)
     session[:user_id] = user.id
   end

 # #5
   def destroy_session(user)
     session[:user_id] = nil
   end

 # #6
   def current_user
     User.find_by(id: session[:user_id])
   end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def user_is_authorized_for_topics?
        current_user && current_user.admin?
   end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_has_comments?
    current_user.comments.count != 0?
  end
  def user_has_posts?
    current_user.posts.count != 0?
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for Questions</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @question do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter question title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter question body" %>
       </div>
       <div class="form-group">
         Mark as Resolved? <%= f.check_box :resolved %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/questions/index.html.erb
<h1>All Questions</h1>

 <% @questions.each do |question| %>
 <div class="media">
   <div class="media-body">
     <h4 class="media-heading">
       <%= link_to question.title, question %>
     </h4>
   </div>
   <div class="col-md-4">
     <%= link_to "New Question", new_question_path, class: 'btn btn-success' %>
   </div>
 </div>
 <% end %>

app/views/questions/new.html.erb
<h1>New Questions</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for Questions</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @question do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter question title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter question body" %>
       </div>
       <div class="form-group">
         <%= f.label :resolved %>
         <%= f.check_box :resolved %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<h1><%= @question.body %></h1>
<h1><%= @question.resolved %></h1>


<div class="col-md-4">
<!-- #5 -->
 <%= link_to "Edit", edit_post_path(@question), class: 'btn btn-success' %>
 <%= link_to "Delete Post", @question, method: :delete, class: 'btn btn-danger',
 data: { confirm: 'Are you sure you want to delete this question?'} %>
</div>